spring.application.name=Run4Spring

spring.datasource.url=jdbc:sqlite:/app/data/mydatabase.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=never
server.port=8081
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**